import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Legion Gears</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="min-h-screen bg-black">
          {/* banner  */}
          <div className="relative">
            <picture>
              <source
                srcSet="/Images/bannerdesktop.jpeg"
                media="(min-width: 768px)" 
              />
              <img
                src="/Images/bannerPhone.jpeg"
                alt="Big Poster"
                className="w-full h-auto"
              />
            </picture>
          </div>

          {/* Cards Section */}
          <div className="p-5 mt-2">
            <h2 className="text-white text-2xl font-bold">Choose your Poison</h2>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-6 p-6">
            <Link href="./helmet">
            <div className="bg-black rounded-lg shadow-md overflow-hidden">
              <Image
                src="/Images/helmet2.jpeg"
                alt="Card 1"
                width={300}
                height={200}
                  className="w-full h-auto "
              />
              <p className="mt-4 text-xl text-white">
                Helmets
              </p>
            </div>
            </Link>

            <Link href="./jackets">
            <div className="bg-black rounded-lg shadow-md overflow-hidden">
              <Image
                src="/Images/jacket1.jpeg"
                alt="Card 1"
                width={300}
                height={200}
                className="w-full h-auto"
              />
              <p className="mt-4 text-xl text-white">
                jackets
              </p>
            </div>
            </Link>
            <Link href="./boots">
            <div className="bg-black rounded-lg shadow-md overflow-hidden">
              <Image
                src="/Images/boots.jpeg"
                alt="Card 1"
                width={300}
                height={200}
                className="w-full h-auto"
              />
              <p className="mt-4 text-xl text-white">
                boots
              </p>
            </div>
            </Link>
            <Link href="./gloves">
            <div className="bg-black rounded-lg shadow-md overflow-hidden">
              <Image
                src="/Images/gloves1.jpeg"
                alt="Card 1"
                width={300}
                height={200}
                className="w-full h-auto"
              />
              <p className="mt-4 text-xl text-white">
                Gloves
              </p>
            </div>
            </Link>

          </div>
          <div className="relative mt-7">
            <picture>
              <source
                srcSet="/Images/banner2desktop.jpeg"
                media="(min-width: 768px)" 
              />
              <img
                src="/Images/banner2Phone.jpeg"
                alt="Big Poster"
                className="w-full h-auto"
              />
            </picture>
          </div>
        </div>
      </div>
    </>
  );
}
